### PR TITLE
Ng 220 v2.0.3

### PR DESCRIPTION
**Pull request by spaul91**
Updated DNANexus reference to CEN VEP config: v1.1.4 -> v1.1.5

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/34)

### CODE REVIEW

**Review by chrispyatt — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/34)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @spaul91)

___
*[`egg5_config_v2.0.3.py` line 2 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/34#-NaRk4KI26dpWBau_vD1:-NaRk4KI26dpWBau_vD2:b-s5ao5q) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/1833b51c4b37acd7109aad865b6bc92d0c2d3925/egg5_config_v2.0.3.py#L2)):*
> ```Python
> assay_name = "CEN" # Core Endo Neuro
> assay_version = "v2.0.2"
> ```

assay version needs incrementing to v2.0.3
___
*[`egg5_config_v2.0.3.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/34#-NaRk0UY7I00D4nE2ji8:-NaRk0UZ7NR6Lvr5i_V1:bo5ypws) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/1833b51c4b37acd7109aad865b6bc92d0c2d3925/egg5_config_v2.0.3.py#L24)):*
> ```Python
> 
> ## for eggd_VEP
> # VEP config file for SNV reports v1.1.4
> ```

this needs changing to say v1.1.5

**Review by chrispyatt — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spaul91)

**Comment by spaul91** [comment]
Sorry confused at next step. Is this for me to merge? @mattgarner ?

**Review by chrispyatt — APPROVED** [review]
No, don't worry. It's for me or Matt to do, I'm just checking whether I'm allowed.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/34#-:-NafPKsLBIRgCfmTDWQr:b-6jzvy7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spaul91)

**Pull request merged**
