### PR TITLE
V3.1.0 changes to DI-700_v3.1.0

### PR DESCRIPTION
**Pull request by rklocke**
**Note:** There are too many changes for GitHub to recognise the JSON as the same file after renaming (no pretty diff) so I created a branch (_DI-700_v3.1.0_) to rename the JSON then branched from there to make changes (v3.1.0_changes) - the DI-700_v3.1.0 branch can then be merged to main later.

**Changes**
- Rename file from v3.0.3 → v3.1.0
- Update artemis app ID from `app-GZ1X5zj4K5ZxyfYPPq4YgGv3` (v1.3.0) → `app-GfKV5204ZF35Z47z31Qzqx90` (v1.4.0)
- Update SNV reports workflow to v2.2.0
- Update CNV reports workflow to v1.2.0
- Update genepanels and g2t file IDs to newer versions
- **cnv_reports**
  - **stage-cnv_generate_bed_vep**
    - Update input names for eggd_generate_bed (exons_nirvana -> exons and nirvana_genes2transcripts -> genes2transcripts) which affects:
      - stage-cnv_generate_bed_vep
      - stage-cnv_generate_bed_excluded
    - Add new string inputs which work with new eggd_dias_batch (v3.1.0) which affects:
      - stage-cnv_generate_bed_vep
      - stage-cnv_generate_bed_excluded
      - stage-cnv_generate_workbook
    - **stage-cnv_generate_workbook**
      - Update `acmg` from true -> 3
      - Add new input `lock_sheet` set to true
- **snv_reports and mosaic_reports**
  - Update input names for eggd_generate_bed (exons_nirvana -> exons and nirvana_genes2transcripts -> genes2transcripts) which affects:
    - stage-rpt_generate_bed_athena
    - stage-rpt_generate_bed_vep
    - stage-rpt_generate_workbook
  - Add new string inputs which work with new eggd_dias_batch (v3.1.0) which affects:
    - stage-rpt_generate_bed_athena
    - stage-rpt_generate_bed_vep
    - stage-rpt_generate_workbook
    - stage-rpt_athena
  - **stage-rpt_vep**
    - Update VEP config file ID cen_vep_config_v1.1.11.json -> cen_vep_config_v1.1.12.json
  - Add inputs for new app eggd_optimised_filtering
  - **stage-rpt_generate_workbook**
    - Remove `CSQ_gnomADg_AF_popmax` and `CSQ_gnomADe_AF_popmax` from exclude_columns because they're now used for filtering
    - Update `acmg` from true -> 3
    - Update `filter` to just filter out EXCLUDE variants since filtering now done within eggd_optimised_filtering
    - Update `human_filter` to reflect new filtering
    - Update `reorder_columns` to include `CSQ_gnomADg_AF_popmax`, `CSQ_gnomADe_AF_popmax` and `MOI`
    - Add new input `lock_sheet` set to true
  - **stage-rpt_athena**
    - Add new input `indication`

**README**
- Update title `dias_CEN_config_GRCh37_v3.0.3.json` -> `dias_CEN_config_GRCh37_v3.1.0.json`
- Update link to eggd_dias_batch from `https://github.com/eastgenomics/dias_batch_running` → `https://github.com/eastgenomics/eggd_dias_batch`
- Update Dias reports version and ID `dias_reports_v2.1.0` and `workflow-GXzkfYj4QPQp9z4Jz4BF09y6` -> `dias_reports_v2.2.0` and `workflow-Gg9Yvj04z4VvPFF3fygp63jy`
- Update Dias CNV reports workflow version and ID `dias_cnvreports_v1.1.0` and `workflow-GXzvJq84XZB1fJk9fBfG88XJ` -> `dias_cnvreports_v1.2.0` and `workflow-Gg9Ybq841Ky1xfYgQ2qjqG3F`
- Update artemis version and app ID v1.3.0 (`app-GZ1X5zj4K5ZxyfYPPq4YgGv3`) -> v1.4.0 (`app-GfKV5204ZF35Z47z31Qzqx90`)
- Update dynamic files genepanels, genes2transcripts, cen_vep_config for SNV/mosaic reports names and IDs and add panel_dump

**Testing**
The config was upload to DNAnexus (https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/data/?scope=project&id.values=file-GgG94Jj4z4VVF2bGQpX4K4bk) and used as an input to Dias batch v3.1.0 to run SNV reports, CNV reports and artemis for two CEN samples:
**Dias batch job**
https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/job/GgG95084z4VkVX3b261Fk31y
**SNV reports jobs**
https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/analysis/GgG95Y04z4VbPzgjJQvx4xx0
https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/analysis/GgG95YQ4z4Vq3yxP24b3GxJy
**CNV reports jobs**
https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/analysis/GgG95Qj4z4VQ6Yqp9FjjV3pX
https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/analysis/GgG95Vj4z4VgV2xpFkB1jXGp
**artemis**
https://platform.dnanexus.com/panx/projects/Gg5Z9VQ4z4Vz8G64byYQbXb6/monitor/job/GgG95Z04z4VZjXZG0bf63QPg

Documentation so far:
https://cuhbioinformatics.atlassian.net/wiki/spaces/DV/pages/3112960008/dias+CEN+config+GRCh37+v3.1.0.json

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55)

### CODE REVIEW

**Review by chrispyatt — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55)* status: all files reviewed, 2 unresolved discussions (waiting on @rklocke)

___
*[`dias_CEN_config_GRCh37_v3.1.0.json` line 142 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55#-NrjG30M05I-NzJiqDdp:-NrjG30M05I-NzJiqDdq:b-cylri5) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/b70fdb68278618cf75aed1de0f79a3f3d47df890/dias_CEN_config_GRCh37_v3.1.0.json#L142)):*
> ```JSON
>                     }
>                 },
>                 "stage-rpt_generate_workbook.clinical_indication": "INPUT-clinical_indications",
> ```

Can we switch off the excluded sheet for snv/indel and mosaic reports with the `--keep_filtered` workbook option? 



_Code quote:_
```JSON
stage-rpt_generate_workbook
```
___
*[`dias_CEN_config_GRCh37_v3.1.0.json` line 152 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55#-NrjGxyiEExigqTqjNfd:-NrjGxyiEExigqTqjNfe:b-4t3pat) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/b70fdb68278618cf75aed1de0f79a3f3d47df890/dias_CEN_config_GRCh37_v3.1.0.json#L152)):*
> ```JSON
>                 "stage-rpt_generate_workbook.summary": "dias",
>                 "stage-rpt_generate_workbook.filter": "bcftools filter -e 'FILTER==\"EXCLUDE\"'",
>                 "stage-rpt_generate_workbook.human_filter": "excluded gnomAD exomes / genomes popmax > 0.1% if gene MOI AD in panel else > 1%, TWE > 5%, synonymous / intronic / intergenic / upstream / downstream / UTRs EXCEPT pathogenic status in ClinVar or DM in HGMD Class",
> ```

marking this to remind me to review/revise. Also in mosaics



_Code quote:_
```JSON
"excluded gnomAD exomes / genomes popmax > 0.1% if gene MOI AD in panel else > 1%, TWE > 5%, synonymous / intronic / intergenic / upstream / downstream / UTRs EXCEPT pathogenic status in ClinVar or DM in HGMD Class"
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[`dias_CEN_config_GRCh37_v3.1.0.json` line 142 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55#-NrjG30M05I-NzJiqDdp:-NrpAh7FETsUUhn9GzV7:b-896fix) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/b70fdb68278618cf75aed1de0f79a3f3d47df890/dias_CEN_config_GRCh37_v3.1.0.json#L142)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Can we switch off the excluded sheet for snv/indel and mosaic reports with the `--keep_filtered` workbook option?
</blockquote></details>

Done.
___
*[`dias_CEN_config_GRCh37_v3.1.0.json` line 152 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55#-NrjGxyiEExigqTqjNfd:-NrpAjI30pJhOIF5Avcs:bgnomu0) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/b70fdb68278618cf75aed1de0f79a3f3d47df890/dias_CEN_config_GRCh37_v3.1.0.json#L152)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

marking this to remind me to review/revise. Also in mosaics
</blockquote></details>

Will wait for review of this

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @chrispyatt and @rklocke)

___
*[`dias_CEN_config_GRCh37_v3.1.0.json` line 152 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55#-NrjGxyiEExigqTqjNfd:-Nrp0-af8_SjFH1o_qnV:b-d5f3zq) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/b70fdb68278618cf75aed1de0f79a3f3d47df890/dias_CEN_config_GRCh37_v3.1.0.json#L152)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

Will wait for review of this
</blockquote></details>

Variants with ClinVar individual or aggregate classifications of Likely pathogenic/Pathogenic are always included, regardless of any other filtering rules. Variants with an HGMD variant class of DM are always included, regardless of other filtering rules. Variants with gnomAD exomes or genomes popmax AF exceeding the threshold associated with the mode of inheritance of the gene are excluded. These thresholds are 0.1% for monoallelic inheritance, 1.0% for all other modes of inheritance. Variants with TWE cohort AF exceeding 5.0% are excluded. Variants with consequences equal to one of the following Sequence Ontology terms are excluded, unless they also have an HGMD variant class of DM?: synonymous\_variant\\intron\_variant\\upstream\_gene\_variant\\downstream\_gene\_variant\\intergenic\_variant\\5\_prime\_UTR\_variant\\3\_prime\_UTR\_variant

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @chrispyatt and @mattgarner)

___
*[`dias_CEN_config_GRCh37_v3.1.0.json` line 152 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55#-NrjGxyiEExigqTqjNfd:-NrquQz7Cx5A0xqnjnmi:b-896fix) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/b70fdb68278618cf75aed1de0f79a3f3d47df890/dias_CEN_config_GRCh37_v3.1.0.json#L152)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Variants with ClinVar individual or aggregate classifications of Likely pathogenic/Pathogenic are always included, regardless of any other filtering rules. Variants with an HGMD variant class of DM are always included, regardless of other filtering rules. Variants with gnomAD exomes or genomes popmax AF exceeding the threshold associated with the mode of inheritance of the gene are excluded. These thresholds are 0.1% for monoallelic inheritance, 1.0% for all other modes of inheritance. Variants with TWE cohort AF exceeding 5.0% are excluded. Variants with consequences equal to one of the following Sequence Ontology terms are excluded, unless they also have an HGMD variant class of DM?: synonymous\_variant\\intron\_variant\\upstream\_gene\_variant\\downstream\_gene\_variant\\intergenic\_variant\\5\_prime\_UTR\_variant\\3\_prime\_UTR\_variant
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55)* status: all files reviewed, 1 unresolved discussion (waiting on @rklocke)

*[a discussion](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55#-Ns8bvmzBl7dqmNoK8fR:-Ns8bvmzBl7dqmNoK8fS:b4kyga4) (no related file):*
Remains open pending g2t and genepanels file approval

___

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/55)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
