### PR TITLE
Di 367 v2.1.0

### PR DESCRIPTION
**Pull request by kjwinfield**
### Update to make CEN config work with cnvreports workflow v1.1.1 and reports workflow v2.1.0
The PRs below document the changes to make egg5_dias_CEN_config compatible with the new versions of the cnvreports workflow (v1.1.1) and the reports workflow (v2.1.0)
- [https://github.com/eastgenomics/egg5_dias_CEN_config/pull/33](https://github.com/eastgenomics/egg5_dias_CEN_config/pull/33) - CNV reports workflow
- [https://github.com/eastgenomics/egg5_dias_CEN_config/pull/32](https://github.com/eastgenomics/egg5_dias_CEN_config/pull/32) - reports workflow

Testing was done in this project: [003_230925_egg5_config_v2.1.0_testing ](https://platform.dnanexus.com/panx/projects/GYfvJVQ440Kqbb6v9zZ4j0GG/data/) and the file ID for egg5_config_v2.1.0.py is `file-GYfz948440KQf2Q2xqB68qxp`.

**10 jobs** were launched using dias batch for each of the following CEN tasks:
- Dias reports with Epic-style manifest
- Dias reports with Gemini-style manifest
- CNV reports with Epic-style manifest
- CNV reports with Gemini-style manifest

Example of launched jobs:
Screenshot from 2023-08-29 15-18-45

Example showing that new versions of apps were used and stage IDs were updated for dias reports
Screenshot from 2023-08-29 15-26-10
Example showing that new versions of apps were used and stage IDs were updated for CNV reports
Screenshot from 2023-08-29 16-00-45

There was a new version of the VEP config released (v1.1.4 --> v1.1.6). A job was investigated to check that this version was used as expected:
Screenshot from 2023-08-29 15-15-51

**Summary**

Screenshot from 2023-08-29 16-07-43

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38)

### CODE REVIEW

**Review by Addy81 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`README.md` line 26 at r10](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38#-Nd5pog1-8QkEeeT0OoJ:-Nd5pog1-8QkEeeT0OoK:bg6ekh0) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/ea45648962b46246b592ff9805e934a88f0823c1/README.md#L26)):*
> ```Markdown
> 
> Dynamic files:
> * genepanels **230602**
> ```

can we have the actual file names please with the extensions?

**Review by Addy81 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kjwinfield)

___
*[`README.md` line 39 at r10](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38#-Nd5qugZ73mZuBLpP9od:-Nd5qug_5qY-U77FEqM0:b-1tmmcf) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/ea45648962b46246b592ff9805e934a88f0823c1/README.md#L39)):*
> ```Markdown
>     * DNAnexus file ID `file-GQGJ3Z84xyx0jp1q65K1Q1jY`
> * additional_regions for CNVs **1.0.1**
>     * DNAnexus file ID `file-GJZQvg0433GkyFZg13K6VV6p`
> ```

Can we also add the cnv calling app version and its inputs please?

**Review by kjwinfield — COMMENTED** [review]
Have put dynamic files into a table to make it more readable.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38#-:-Nd5zHWYCPAMT6NWX_kK:b5kc6yg)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Addy81)

___
*[`README.md` line 26 at r10](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38#-Nd5pog1-8QkEeeT0OoJ:-Nd5zB9QBZKXBeESO9HQ:b-896fix) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/ea45648962b46246b592ff9805e934a88f0823c1/README.md#L26)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

can we have the actual file names please with the extensions?
</blockquote></details>

Done.
___
*[`README.md` line 39 at r10](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38#-Nd5qugZ73mZuBLpP9od:-Nd5zGJ-Ak9chR-Eu3FL:b-896fix) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/ea45648962b46246b592ff9805e934a88f0823c1/README.md#L39)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Can we also add the cnv calling app version and its inputs please?
</blockquote></details>

Done.

**Review by Addy81 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @kjwinfield)

___
*[`README.md` line 8 at r13](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38#-Nd64KudA78GsD8zFITM:-Nd64KudA78GsD8zFITN:bt3eksq) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/a49eeca780a6116695e03bd67d6053017d1c32f0/README.md#L8)):*
> ```Markdown
> dias_batch_running ([https://github.com/eastgenomics/dias_batch_running](https://github.com/eastgenomics/dias_batch_running)) is a Python module that runs the Dias pipeline for germline sequence data analysis on DNAnexus. The egg5_dias_CEN_config specifies the executables and their input files to be used in the Dias pipeline for analysing CEN data.
> 
> New versions of apps and app inputs for use in the Dias pipeline can be updated in the config without needing to update the pipeline itself
> ```

fullstop 
___
*[`README.md` line 12 at r13](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38#-Nd64Mz3B9qsi_s050Mn:-Nd64Mz3B9qsi_s050Mo:b-ct4yju) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/a49eeca780a6116695e03bd67d6053017d1c32f0/README.md#L12)):*
> ```Markdown
> ## Parts of the config
> * GATKgCNV_call
>     * specifies the app ID and inputs for CNV calling
> ```

fullstop
___
*[`egg5_config_v2.1.0.py` line 138 at r13](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38#-Nd64Bbd9AMWrn9An1-s:-Nd64Bbd9AMWrn9An1-t:b-s5068n) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/a49eeca780a6116695e03bd67d6053017d1c32f0/egg5_config_v2.1.0.py#L138)):*
> ```Python
>     "{}.config_file ID".format(cnv_vep_stage_id): cnv_vep_config,
>     "{}.config_file".format(cnv_vep_stage_id): "",
>     # inputs for generate bed for excluded app
> ```

there's a request to add the report sheet to cnv reports also. Waiting to see if we should add it now so might ask to add the acmg flag.

**Review by Addy81 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/38)* status: 2 of 3 files reviewed, all discussions resolved

**Pull request merged**
