### PR TITLE
v3.1.1

### PR DESCRIPTION
**Pull request by growland2**
Updated to use new snv/cnv workflows and latest vep config

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60)

### CODE REVIEW

**Comment by growland2** [comment]
[!Note]

Awaiting updated g2t and genepanels files before merging

**Review by Addy81 — APPROVED** [review]
Approving but nor merging as additional changes will be needed when g2t/genepanels are ready.

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-:-Nu4aD_kEpA5DXZUSPbm:b2d81k7)* status: 1 of 2 files reviewed, all discussions resolved

___
*[`dias_CEN_config_GRCh37_v3.1.1.json` line 6 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-Nu4a-xR290InlYCfzU4:-Nu4a-xR290InlYCfzU5:b-lcfe1c) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/de3c8d45958f0d1a4eb552815aa4b30a197e1206/dias_CEN_config_GRCh37_v3.1.1.json#L6)):*
> ```JSON
>     "cnv_call_app_id": "app-GZ4pXxj4xG062Bj5zjgP1Bb0",
>     "artemis_app_id": "app-GfKV5204ZF35Z47z31Qzqx90",
>     "snv_report_workflow_id": "workflow-Gj2by604ZxY18BX86Jy0b9Xv",
> ```

dias_reports_v2.2.1 :lgtm: 
___
*[`dias_CEN_config_GRCh37_v3.1.1.json` line 7 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-Nu4aBXi1MtVjMHiuFdM:-Nu4aBXi1MtVjMHiuFdN:b2icmx1) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/de3c8d45958f0d1a4eb552815aa4b30a197e1206/dias_CEN_config_GRCh37_v3.1.1.json#L7)):*
> ```JSON
>     "artemis_app_id": "app-GfKV5204ZF35Z47z31Qzqx90",
>     "snv_report_workflow_id": "workflow-Gj2by604ZxY18BX86Jy0b9Xv",
>     "cnv_report_workflow_id": "workflow-Gj2fqVQ41Ky9BKJjkxB2KbzF",
> ```

dias_cnvreports_v1.2.0 :lgtm_strong: 
___
*[`dias_CEN_config_GRCh37_v3.1.1.json` line 65 at r1](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-Nu4_nLwBTJ-GMXQ0_vS:-Nu4_nLwBTJ-GMXQ0_vT:b-dkxt79) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/de3c8d45958f0d1a4eb552815aa4b30a197e1206/dias_CEN_config_GRCh37_v3.1.1.json#L65)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-Ggy5b904z6j5k3Gfb3Kk2gqG"
> ```

cen_vep_config_v1.1.13.json

**Review by Addy81 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @growland2)

___
*[`README.md` line 30 at r2](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-NucbDHX2ui4E24Az3lU:-NucbDHX2ui4E24Az3lV:b-sco4v4) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/71689299bb258106de060f37a6a68dd32407ba06/README.md#L30)):*
> ```Markdown
>     * DNAnexus workflow ID: `workflow-Gj2by604ZxY18BX86Jy0b9Xv`
> * Dias CNV reports: **dias_cnvreports_v1.2.0**
>     * DNAnexus workflow ID: `workflow-Gj2fqVQ41Ky9BKJjkxB2KbzF`
> ```

This workflow ID is not the same as config and not valid. I assume it needs to be "workflow-Gj77F9041Ky3Vp045gpKx0B4 ? 
___
*[`README.md` line 45 at r2](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-Nucb0Q2DMtTpkt6ALue:-Nucb0Q30b2tve6usl8u:bxxclil) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/71689299bb258106de060f37a6a68dd32407ba06/README.md#L45)):*
> ```Markdown
> | genepanels | **240402_genepanels.tsv** | `file-Gj771Q8433GQQZz0gp966kG5` |
> | exons_nirvana | **GCF_000001405.25_GRCh37.p13_genomic.exon_5bp_v2.0.0.tsv** | `file-GF611Z8433Gk7gZ47gypK7ZZ` |
> | genes2transcripts | **240402_g2t.tsv** | `file-Gj770X8433Gb506pjq1PxXG9` |
> ```

New g2t and genepanels same as in the config :lgtm_strong: 
___
*[`dias_CEN_config_GRCh37_v3.1.1.json` line 6 at r2](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-Nuc_u-l30Ryt-eeHmcq:-Nuc_u-l30Ryt-eeHmcr:b-ibbzvg) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/71689299bb258106de060f37a6a68dd32407ba06/dias_CEN_config_GRCh37_v3.1.1.json#L6)):*
> ```JSON
>     "cnv_call_app_id": "app-GZ4pXxj4xG062Bj5zjgP1Bb0",
>     "artemis_app_id": "app-GfKV5204ZF35Z47z31Qzqx90",
>     "snv_report_workflow_id": "workflow-Gj766G04ZxY0GVPV0GvXxj9q",
> ```

dias_reports_v2.2.1
___
*[`dias_CEN_config_GRCh37_v3.1.1.json` line 7 at r2](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-Nuca1vs4hHDLUq2e8zx:-Nuca1vs4hHDLUq2e8zy:b-o89xi6) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/71689299bb258106de060f37a6a68dd32407ba06/dias_CEN_config_GRCh37_v3.1.1.json#L7)):*
> ```JSON
>     "artemis_app_id": "app-GfKV5204ZF35Z47z31Qzqx90",
>     "snv_report_workflow_id": "workflow-Gj766G04ZxY0GVPV0GvXxj9q",
>     "cnv_report_workflow_id": "workflow-Gj77F9041Ky3Vp045gpKx0B4",
> ```

dias_cnvreports_v1.2.0 - currently being signed off. 
___
*[`dias_CEN_config_GRCh37_v3.1.1.json` line 9 at r2](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-NucaRVc5ypnOd1HdUIv:-NucaRVe7F2lGl9LHlv2:b-sb7sh9) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/71689299bb258106de060f37a6a68dd32407ba06/dias_CEN_config_GRCh37_v3.1.1.json#L9)):*
> ```JSON
>     "cnv_report_workflow_id": "workflow-Gj77F9041Ky3Vp045gpKx0B4",
>     "reference_files": {
>         "genepanels": "project-Fkb6Gkj433GVVvj73J7x8KbV:file-Gj771Q8433GQQZz0gp966kG5",
> ```

240402_genepanels.tsv :lgtm: 
___
*[`dias_CEN_config_GRCh37_v3.1.1.json` line 11 at r2](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-Nucahsh44L7p0dCtd3P:-Nucahsh44L7p0dCtd3Q:b-p9kglu) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/71689299bb258106de060f37a6a68dd32407ba06/dias_CEN_config_GRCh37_v3.1.1.json#L11)):*
> ```JSON
>         "genepanels": "project-Fkb6Gkj433GVVvj73J7x8KbV:file-Gj771Q8433GQQZz0gp966kG5",
>         "exons_nirvana": "project-Fkb6Gkj433GVVvj73J7x8KbV:file-GF611Z8433Gk7gZ47gypK7ZZ",
>         "genes2transcripts": "project-Fkb6Gkj433GVVvj73J7x8KbV:file-Gj770X8433Gb506pjq1PxXG9",
> ```

240402_g2t.tsv :lgtm_strong: 
___
*[`dias_CEN_config_GRCh37_v3.1.1.json` line 65 at r2](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-NucasgY0Bz-v73bzfmH:-NucasgY0Bz-v73bzfmI:b-dkxt79) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/71689299bb258106de060f37a6a68dd32407ba06/dias_CEN_config_GRCh37_v3.1.1.json#L65)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-Ggy5b904z6j5k3Gfb3Kk2gqG"
> ```

cen_vep_config_v1.1.13.json

**Review by Addy81 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @growland2)

___
*[`README.md` line 30 at r2](https://reviewable.io/reviews/eastgenomics/egg5_dias_CEN_config/60#-NucbDHX2ui4E24Az3lU:-NuccZRV1qAjKKbgx5ER:bb6tyiv) ([raw file](https://github.com/eastgenomics/egg5_dias_CEN_config/blob/71689299bb258106de060f37a6a68dd32407ba06/README.md#L30)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

This workflow ID is not the same as config and not valid. I assume it needs to be "workflow-Gj77F9041Ky3Vp045gpKx0B4 ?
</blockquote></details>

DONE

**Pull request merged**
